class PrintingComments extends ConsoleProgram {
  
  
  
  public void run() {

    
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    System.out.println("*************");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*           *");
    System.out.println("*************");
    
  }
}
